module control_unit(
  input [4:0] opcode,
  output reg st,ld,beq,bgt,ret,wb,u_branch,call,add,sub,cmp,mul,div,mod,lsl,lsr,asr,is_or,is_and,is_not,mov);
  always@(*) begin
    case(opcode)
      5'b00000:begin 
        st = 0;
        ld = 0;
        beq = 0;
        bgt = 0;
        ret = 0;
        wb = 1;
        u_branch = 0;
        call = 0;
        add = 1;
        sub = 0;
        cmp = 0;
        mul = 0;
        div = 0;
        mod = 0;
        lsl = 0;
        lsr = 0;
        asr = 0;
        is_or = 0;
        is_and = 0;
        is_not = 0;
        mov = 0;
      end
      5'b00001:begin 
        st = 0;
        ld = 0;
        beq = 0;
        bgt = 0;
        ret = 0;
        wb = 1;
        u_branch = 0;
        call = 0;
        add = 0;
        sub = 1;
        cmp = 0;
        mul = 0;
        div = 0;
        mod = 0;
        lsl = 0;
        lsr = 0;
        asr = 0;
        is_or = 0;
        is_and = 0;
        is_not = 0;
        mov = 0;
      end
      5'b00010:begin 
        st = 0;
        ld = 0;
        beq = 0;
        bgt = 0;
        ret = 0;
        wb = 1;
        u_branch = 0;
        call = 0;
        add = 0;
        sub = 0;
        cmp = 0;
        mul = 1;
        div = 0;
        mod = 0;
        lsl = 0;
        lsr = 0;
        asr = 0;
        is_or = 0;
        is_and = 0;
        is_not = 0;
        mov = 0;
      end
      5'b00011:begin 
        st = 0;
        ld = 0;
        beq = 0;
        bgt = 0;
        ret = 0;
        wb = 1;
        u_branch = 0;
        call = 0;
        add = 0;
        sub = 0;
        cmp = 0;
        mul = 0;
        div = 1;
        mod = 0;
        lsl = 0;
        lsr = 0;
        asr = 0;
        is_or = 0;
        is_and = 0;
        is_not = 0;
        mov = 0;
      end
      5'b00100:begin 
        st = 0;
        ld = 0;
        beq = 0;
        bgt = 0;
        ret = 0;
        wb = 1;
        u_branch = 0;
        call = 0;
        add = 0;
        sub = 0;
        cmp = 0;
        mul = 0;
        div = 0;
        mod = 1;
        lsl = 0;
        lsr = 0;
        asr = 0;
        is_or = 0;
        is_and = 0;
        is_not = 0;
        mov = 0;
      end
      5'b00101:begin 
        st = 0;
        ld = 0;
        beq = 0;
        bgt = 0;
        ret = 0;
        wb = 1;
        u_branch = 0;
        call = 0;
        add = 0;
        sub = 0;
        cmp = 1;
        mul = 0;
        div = 0;
        mod = 0;
        lsl = 0;
        lsr = 0;
        asr = 0;
        is_or = 0;
        is_and = 0;
        is_not = 0;
        mov = 0;
      end
      5'b00110:begin 
        st = 0;
        ld = 0;
        beq = 0;
        bgt = 0;
        ret = 0;
        wb = 1;
        u_branch = 0;
        call = 0;
        add = 0;
        sub = 0;
        cmp = 0;
        mul = 0;
        div = 0;
        mod = 0;
        lsl = 0;
        lsr = 0;
        asr = 0;
        is_or = 0;
        is_and = 1;
        is_not = 0;
        mov = 0;
      end
      5'b00111:begin 
        st = 0;
        ld = 0;
        beq = 0;
        bgt = 0;
        ret = 0;
        wb = 1;
        u_branch = 0;
        call = 0;
        add = 0;
        sub = 0;
        cmp = 0;
        mul = 0;
        div = 0;
        mod = 0;
        lsl = 0;
        lsr = 0;
        asr = 0;
        is_or = 1;
        is_and = 0;
        is_not = 0;
        mov = 0;
      end
      5'b01000:begin 
        st = 0;
        ld = 0;
        beq = 0;
        bgt = 0;
        ret = 0;
        wb = 1;
        u_branch = 0;
        call = 0;
        add = 0;
        sub = 0;
        cmp = 0;
        mul = 0;
        div = 0;
        mod = 0;
        lsl = 0;
        lsr = 0;
        asr = 0;
        is_or = 0;
        is_and = 0;
        is_not = 1;
        mov = 0;
      end
      5'b01001:begin 
        st = 0;
        ld = 0;
        beq = 0;
        bgt = 0;
        ret = 0;
        wb = 1;
        u_branch = 0;
        call = 0;
        add = 0;
        sub = 0;
        cmp = 0;
        mul = 0;
        div = 0;
        mod = 0;
        lsl = 0;
        lsr = 0;
        asr = 0;
        is_or = 0;
        is_and = 0;
        is_not = 0;
        mov = 1;
      end
      5'b01010:begin 
        st = 0;
        ld = 0;
        beq = 0;
        bgt = 0;
        ret = 0;
        wb = 1;
        u_branch = 0;
        call = 0;
        add = 0;
        sub = 0;
        cmp = 0;
        mul = 0;
        div = 0;
        mod = 0;
        lsl = 1;
        lsr = 0;
        asr = 0;
        is_or = 0;
        is_and = 0;
        is_not = 0;
        mov = 0;
      end
      5'b01011:begin 
        st = 0;
        ld = 0;
        beq = 0;
        bgt = 0;
        ret = 0;
        wb = 1;
        u_branch = 0;
        call = 0;
        add = 0;
        sub = 0;
        cmp = 0;
        mul = 0;
        div = 0;
        mod = 0;
        lsl = 0;
        lsr = 1;
        asr = 0;
        is_or = 0;
        is_and = 0;
        is_not = 0;
        mov = 0;
      end
      5'b01100:begin 
        st = 0;
        ld = 0;
        beq = 0;
        bgt = 0;
        ret = 0;
        wb = 1;
        u_branch = 0;
        call = 0;
        add = 0;
        sub = 0;
        cmp = 0;
        mul = 0;
        div = 0;
        mod = 0;
        lsl = 0;
        lsr = 0;
        asr = 1;
        is_or = 0;
        is_and = 0;
        is_not = 0;
        mov = 0;
      end
      5'b01101:begin 
        st = 0;
        ld = 0;
        beq = 0;
        bgt = 0;
        ret = 0;
        wb = 0;
        u_branch = 0;
        call = 0;
        add = 0;
        sub = 0;
        cmp = 0;
        mul = 0;
        div = 0;
        mod = 0;
        lsl = 0;
        lsr = 0;
        asr = 0;
        is_or = 0;
        is_and = 0;
        is_not = 0;
        mov = 0;
      end
      5'b01110:begin 
        st = 0;
        ld = 1;
        beq = 0;
        bgt = 0;
        ret = 0;
        wb = 1;
        u_branch = 0;
        call = 0;
        add = 1;
        sub = 0;
        cmp = 0;
        mul = 0;
        div = 0;
        mod = 0;
        lsl = 0;
        lsr = 0;
        asr = 0;
        is_or = 0;
        is_and = 0;
        is_not = 0;
        mov = 0;
      end
      5'b01111:begin 
        st = 1;
        ld = 0;
        beq = 0;
        bgt = 0;
        ret = 0;
        wb = 0;
        u_branch = 0;
        call = 0;
        add = 1;
        sub = 0;
        cmp = 0;
        mul = 0;
        div = 0;
        mod = 0;
        lsl = 0;
        lsr = 0;
        asr = 0;
        is_or = 0;
        is_and = 0;
        is_not = 0;
        mov = 0;
      end
      5'b10000:begin 
        st = 0;
        ld = 0;
        beq = 1;
        bgt = 0;
        ret = 0;
        wb = 0;
        u_branch = 0;
        call = 0;
        add = 0;
        sub = 0;
        cmp = 0;
        mul = 0;
        div = 0;
        mod = 0;
        lsl = 0;
        lsr = 0;
        asr = 0;
        is_or = 0;
        is_and = 0;
        is_not = 0;
        mov = 0;
      end
      5'b10001:begin 
        st = 0;
        ld = 0;
        beq = 0;
        bgt = 1;
        ret = 0;
        wb = 0;
        u_branch = 0;
        call = 0;
        add = 0;
        sub = 0;
        cmp = 0;
        mul = 0;
        div = 0;
        mod = 0;
        lsl = 0;
        lsr = 0;
        asr = 0;
        is_or = 0;
        is_and = 0;
        is_not = 0;
        mov = 0;
      end
      5'b10010:begin 
        st = 0;
        ld = 0;
        beq = 0;
        bgt = 0;
        ret = 0;
        wb = 0;
        u_branch = 1;
        call = 0;
        add = 0;
        sub = 0;
        cmp = 0;
        mul = 0;
        div = 0;
        mod = 0;
        lsl = 0;
        lsr = 0;
        asr = 0;
        is_or = 0;
        is_and = 0;
        is_not = 0;
        mov = 0;
      end
      5'b10011:begin 
        st = 0;
        ld = 0;
        beq = 0;
        bgt = 0;
        ret = 0;
        wb = 1;
        u_branch = 0;
        call = 1;
        add = 0;
        sub = 0;
        cmp = 0;
        mul = 0;
        div = 0;
        mod = 0;
        lsl = 0; 
        lsr = 0;
        asr = 0;
        is_or = 0;
        is_and = 0;
        is_not = 0;
        mov = 0;
      end
      5'b10100:begin 
        st = 0;
        ld = 0;
        beq = 0;
        bgt = 0;
        ret = 1;
        wb = 0;
        u_branch = 0;
        call = 0;
        add = 0;
        sub = 0;
        cmp = 0;
        mul = 0;
        div = 0;
        mod = 0;
        lsl = 0;
        lsr = 0;
        asr = 0;
        is_or = 0;
        is_and = 0;
        is_not = 0;
        mov = 0;
      end
      default : begin
        st = 0;
        ld = 0;
        beq = 0;
        bgt = 0;
        ret = 0;
        wb = 0;
        u_branch = 0;
        call = 0;
        add = 0;
        sub = 0;
        cmp = 0;
        mul = 0;
        div = 0;
        mod = 0;
        lsl = 0;
        lsr = 0;
        asr = 0;
        is_or = 0;
        is_and = 0;
        is_not = 0;
        mov = 0;
      end
    endcase
  end
endmodule
